[editor]
soft-wrap.enable = true

[keys.normal]
C-s = ":write"
C-n = ":toggle line-numbers"
C = ["extend_to_line_end", "change_selection"]
D = ["extend_to_line_end", "delete_selection"]
x = "delete_selection"
S-v = "extend_to_line_bounds"

[keys.select]
x = "delete_selection"

[keys.normal.d]
d = ["extend_to_line_bounds", "delete_selection", "normal_mode"]

[keys.normal.g]
t = "goto_next_buffer"
T = "goto_previous_buffer"
